src/FilmonAPI.cpp, src/FilmonAPI.h
This should fix the Win32 build failure mentioned in https://github.com/xbmc/xbmc/pull/6665
=> fix build for Win32

pvr.filmon/addon.xml, pvr.filmon/changelog.txt, src/PVRFilmonData.cpp
If nobody objects this is going in later today.
=> Sync with API 1.9.6

pvr.filmon/addon.xml, pvr.filmon/changelog.txt, src/client.cpp
Fixes https://launchpadlibrarian.net/206716559/buildlog_ubuntu-vivid-amd64.kodi-pvr-filmon_0.5.5-3~vivid_BUILDING.txt.gz
=> Fix debian build

pvr.filmon/addon.xml, pvr.filmon/changelog.txt, src/client.cpp
Add-on part of https://github.com/xbmc/xbmc/pull/7536
=> Minimal support for PVR API 2.1.0

pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt
Add-on part of https://github.com/xbmc/xbmc/pull/7570
=> Automatically fill in platform and library name

pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt
Addon part of xbmc/xbmc#7626
Add on currently using 1.9.7 API compatibility code
No further changes required for minimal support
=> Bump add-on for PVR API 3.0.0 (Compatibility mode)

pvr.filmon/resources/language/resource.language.en_gb/strings.po, pvr.filmon/resources/settings.xml, src/FilmonAPI.cpp, src/client.cpp, src/client.h
Addon tries to use HD stream, but stream is stopped after 3 minutes for free accounts. This PR adds option to prefer SD streams which can be used by free accounts.
=> Add option to select SD streams fixes #16204

pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt, src/FilmonAPI.cpp, src/client.cpp
For details refer to https://github.com/xbmc/xbmc/pull/8736 (API 5.0.0) and https://github.com/xbmc/xbmc/pull/8896 (API 4.2.0).
Before this PR can go in, https://github.com/xbmc/xbmc/pull/8736 must be merged.
=> Implement PVR API 4.2.0 and 5.0.0

src/FilmonAPI.cpp, src/PVRFilmonData.cpp
=> fix build breaker

pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt, src/PVRFilmonData.cpp
Refer to https://github.com/xbmc/xbmc/pull/9290 and https://github.com/xbmc/xbmc/pull/9295 for details.
=> PVR API 5.1.0

pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt, src/PVRFilmonData.h, src/client.cpp, src/client.h
https://github.com/xbmc/xbmc/pull/9804 and https://github.com/xbmc/xbmc/pull/9671 for reference
=> Fix includes

pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt, src/FilmonAPI.cpp
* Fix EPG after API change
* Update addon.xml.in
* Update changelog.txt
=> Fix EPG after API change

debian/kodi-pvr-filmon.install
This also affects Krypton. After view, please merge into the Krypton branch as well.
=> fix install path

CMakeLists.txt, pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt
Related to kodi Pull Request xbmc/xbmc#12029
Not merge in before is in Kodi!
=> change to automatic depends set on addon.xml

pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt, src/client.cpp
related to Kodi pull request xbmc/xbmc#12109
=> remove no more needed version functions

debian/control, pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt
This is related to xbmc/xbmc#12114 and xbmc/xbmc#12116
=> Update addon Version related to Kodi changes

pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt, src/client.cpp
Related kodi PR: https://github.com/xbmc/xbmc/pull/12303
=> Added minimalistic support for PVR Addon API 5.3.0

src/PVRFilmonData.cpp
Logic was wrong in the initial implementation
I believe this should simplify it and also correct it.
=> update to GetChannelStreamProperties()

pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt, src/PVRFilmonData.h, src/client.cpp
=> [cleanup] remove StdString usage

pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt, src/client.cpp
=> PVR API 5.8.0

pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt, src/client.cpp
=> PVR API 5.10.0

pvr.filmon/addon.xml.in, pvr.filmon/changelog.txt, src/PVRFilmonData.cpp
For details see xbmc/xbmc#14086
=> PVR API 5.10.1
